### ISSUE TITLE
Plugin removes Preact from node_modules

### ISSUE THREAD

**Issue by binury** [SaraVieira/preact-cli-plugin-flow#3]
Adding `preact-cli-plugin-flow` on a fresh installation of `Preact` causes the folder to be deleted.

**Comment by binury** [comment]
Just guessing/intuition but I'd wager the post-installation scripts are configured assuming the installation is done with NPM which causes a conflict for users who have opted into using the `--yarn` flag.

**Comment by binury** [comment]
Modifying `preact-cli-plugin-flow/bin/index.js` to test for the existence of yarn.lock could then allow the post installation to complete using the user's chosen package manager and prevent npm from breaking the depedencies

**Comment by SaraVieira** [comment]
Hi @teddy-error, 

So sorry about the issue 😕

I will get on this today!  It is probably what you are saying 

Thank you for pointing it out!

**Comment by moebiusmania** [comment]
hi, unfortunately this is still happening
